version: '3.9'
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - my_network
    depends_on:
      - nginx-service
  nginx-service:
    build:
      context: ./nginx-service
      dockerfile: Dockerfile
    ports:
      - "2001:80"  # Map port 2001 on your host to port 80 in the container
    volumes:
      - nginx-certs:/nginx-certs
    networks:
      - my_network

networks:
  my_network:

volumes:
  nginx-certs: