version: '3.9'
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - my_network
    depends_on:
      - nginx-service
    volumes:
      - nginx-certs:/nginx-certs
    ports:
      - "2005:2005"
  nginx-service:
    build:
      context: ./nginx-service
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - nginx-certs:/nginx-certs
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:443"]
      interval: 5s
      timeout: 10s
      retries: 3


networks:
  my_network:

volumes:
  nginx-certs: