version: '3.15'
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.10
    depends_on:
      - nginx-service
      - redis
      - mysql-server
    ports:
      - "2005:2005"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      SERVER_IP_ADDRESS: ${SERVER_IP_ADDRESS}
    volumes:
      - nginx-certs:/nginx-certs
  nginx-service:
    build:
      context: ./nginx-service
      dockerfile: Dockerfile
      args:
        SERVER_IP_ADDRESS: ${SERVER_IP_ADDRESS}
    ports:
      - "443:443"
    volumes:
      - nginx-certs:/nginx-certs
    networks:
      my_network:
        ipv4_address: 192.168.1.20
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:443"]
      interval: 5s
      timeout: 10s
      retries: 3
  redis:
    image: redis:latest
    networks:
      my_network:
        ipv4_address: 192.168.1.30
  mysql-server:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    networks:
      my_network:
        ipv4_address: 192.168.1.40
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  nginx-certs: